### ISSUE TITLE
Integrating into Battery Controller

### ISSUE THREAD

**Issue by flatmax** [dxoverdy/Alpha2MQTT#15]
Lovely piece of work - great detail and information. Amazing that you got the charge/discharge working.

I wrote a battery controller and I would love to integrate your work into it. Here is a link :
https://github.com/flatmax/BatteryController

I have a setup where I am already probing the fuse box for production/consumption using an Enphase Envoy. I also now have two ACR100R meters, one for consumption and one for production. So I have a few ways to get production/consumption data.

If I want to control the alpha ESS batteries, then I guess I can construct your hardware. But is there any reason why we can't use your software directly through a USB to RS845 adapter ? If so then will your code compile down on linux ?

**Comment by inmanelectric** [comment]
> Lovely piece of work - great detail and information. Amazing that you got the charge/discharge working.
> 
> I wrote a battery controller and I would love to integrate your work into it. Here is a link : https://github.com/flatmax/BatteryController
> 
> I have a setup where I am already probing the fuse box for production/consumption using an Enphase Envoy. I also now have two ACR100R meters, one for consumption and one for production. So I have a few ways to get production/consumption data.
> 
> If I want to control the alpha ESS batteries, then I guess I can construct your hardware. But is there any reason why we can't use your software directly through a USB to RS845 adapter ? If so then will your code compile down on linux ?
>
>i am new here 
I would like to know if 
If it would be possible to get the Alpha ESS M48112-s batteries to communicate with a Deye 29.9 kilowatt three phase inverter via a RS 485 / modbus device 
Is there a way ?
