### ISSUE TITLE
Disable/shutdown PV inverter when energy prices turn negative

### ISSUE THREAD

**Issue by RolfDeL** [dxoverdy/Alpha2MQTT#23]
Hi Daniel,

I've been looking in to the register set but can not find if you can disable/shutdown the PV production when energy prices turn negative.
I have a dynamic energy contact. 

Kind regards

**Comment by ffrog8** [comment]
I don't think pv can be shut off. You can limit the % fees in to 0, which will stop exporting over what the house is using. Have to make sure that there are no other dispatch commands are active at the same time or the % is ignored.
