### ISSUE TITLE
PDF link no longer works

### ISSUE THREAD

**Issue by SorX14** [dxoverdy/Alpha2MQTT#4]
Looks like AlphaESS have changed the location of the PDF. An alternative is https://www.alpha-ess.de/images/downloads/handbuecher/AlphaESS_Register_Parameter_List.pdf found from this page: https://www.alpha-ess.de/downloads

Seems to be slighly less information in there, for example `system laguage` (sic) no longer tells you what the options are.

**Comment by dxoverdy** [comment]
Thanks for the note (and generous extra super large coffee with all the sprinkles by the way, that was very kind)
I will update the links appropriately.  Further, the details of communication have been separated out into https://www.alpha-ess.de/images/downloads/handbuecher/AlphaESS-Handbuch_SMILE_ModBus_RTU_TCP_V2.pdf
