### ISSUE TITLE
Discharge mode

### ISSUE THREAD

**Issue by jt1971** [dxoverdy/Alpha2MQTT#6]
Hi. I've been really impressed with the alpha2mqtt, both hardware and the software. I have mine connected to HA and have therefore used your excellent yaml code for the mqtt and the controls.  Everything is working fine other than:
1. With the exception of the charge mode, 'Dispatch mode' always states 'unknown' (the ModBus arduino code is reporting 'unknown'
2. If I try to select discharge mode (to dump excess battery charge into the car for example), although the response status says 'setDischargeStatus' and and '0' for failure detail, the dispatch power does not budge from 32000W and other parameters in the Information entity box remain unchanged.

I'm not entirely sure how I can diagnose further.  HA is sending out the correct mqtt message as far as I can tell (using MQTT explorer on my Mac).

Apologies if a bit of a lame question, but I'm not sure how to progress to resolve this?

Thanks!

**Comment by ettiennecoetzee** [comment]
Hi, mine says the same. What inverter do you have?

**Comment by ettiennecoetzee** [comment]
My discharge mode on the Smile G3S5 is also not working. I set the target soc and max dc wattage and 2 hour time span, but no discharge. Let me know if I can share specific details so that you can trouble shoot? @dxoverdy

**Comment by dxoverdy** [comment]
I’ve no idea what could be causing this as the steps are the same.  But I’m
thinking it may be down to the current regulation set in the system.

Can you read out regulation please and let me know what it is?

**Comment by dxoverdy** [comment]
Read out via handled register 0x1000


#define REG_SAFETY_TEST_RW_GRID_REGULATION 0x1000

I’m wondering if your inverter is set to a grid regulation which doesn’t
currently (or suggests) it doesn’t allow discharge.

Please let me know the return value and description.  Mine for example is
16 / G99

**Comment by ettiennecoetzee** [comment]
Data value: 10
Formatted: NRS097-2-1
Function code:3
Raw data: [0,10]

**Comment by dxoverdy** [comment]
Send four separate MQTT messages to this topic:
Alpha2MQTT/request/write/register/raw/data

-- Dispatch Start
`{
    "registerAddress": "0x0880",
    "dataBytes": 2,
    "value": 1
}`

-- Power (1000W discharge)
`{
    "registerAddress": "0x0881",
    "dataBytes": 4,
    "value": 33000
}`

-- Time (Just two 2 minutes)
`{
    "registerAddress": "0x0887",
    "dataBytes": 4,
    "value": 120
}`


-- SOC (down to 15%) 15 / 0.4 = 37.5, so 38 will do
{
    "registerAddress": "0x0886",
    "dataBytes": 2,
    "value": 38
}

-- Mode - SOC Control (2)
`{
    "registerAddress": "0x0885",
    "dataBytes": 2,
    "value": 2
}`

You don't have to rush them.  Allow a few seconds before each, allowing plenty of time for copy and paste.  I am wondering if pinging the four steps required to activate discharge (Start Dispatch, Set Power, Set Duration, Set Minimum SOC and Set Mode) if issued separately works.  If it does that would suggest when Alpha2MQTT sends the messages, it is sending them all too quickly.

**Comment by ettiennecoetzee** [comment]
Done. No discharge.

This is what my Alpha Control Dash looks like:
![image](https://github.com/dxoverdy/Alpha2MQTT/assets/53652614/1987e12c-03b5-4952-87c6-be4d589b5de6)

**Comment by dxoverdy** [comment]
Whoahh that percentage needs a bit of work.  What is your battery
percentage currently (proper) and why is battery power zero?

**Comment by dxoverdy** [comment]
Does the same set of commands, albeit with 31000 power start charging at
1000W?

**Comment by ettiennecoetzee** [comment]
Battery percentage was 90%. I think the power was zero since it wasnt charging or discharging. 
I changed the 33000 to 1000. This is what happened:
![image](https://github.com/dxoverdy/Alpha2MQTT/assets/53652614/006a57fe-e1d4-4292-8d6c-c1574258576e)

**Comment by dxoverdy** [comment]
Any idea why the battery is not either discharging or charging?

**Comment by dxoverdy** [comment]
Either way the percentage reading is unexpected.  Whilst it may not be to
blame it doesn’t fill me with confidence anyway.

If you want to do what others have done, ping me a private message with
details to access your home assistant instance (preferably a separate
account for me so you can disable it after) and I’ll have a Quick Look
around.

**Comment by jt1971** [comment]
As an aside, my target soc has always shown spurious figures but still works great on my Smile5.Sent from my iPhone.On 9 Jan 2024, at 07:27, Daniel Young ***@***.***> wrote:﻿
Either way the percentage reading is unexpected.  Whilst it may not be to

blame it doesn’t fill me with confidence anyway.



If you want to do what others have done, ping me a private message with

details to access your home assistant instance (preferably a separate

account for me so you can disable it after) and I’ll have a Quick Look

around.







On Tue, 9 Jan 2024 at 07:13, Ettienne Coetzee ***@***.***>

wrote:

**Comment by dxoverdy** [comment]
So it looks like that safety regulation may prevent discharge from battery
to grid.  After all, the code to charge is the same code to discharge, one
just uses a number above 32000 and the other uses one below.  I can see the
other fella in this chat now discharges fine so not sure what he’s done to
get it working….

Perhaps mail alpha and ask if your regulation prevents discharge.

(You can always change it to something we know such as G99 to try)

Good luck!

**Comment by ettiennecoetzee** [comment]
Sorry for bugging you again. Just a quick question. I want to try and set my 0x1000 register to your value (G99). This might be a dumb question, but how do I go about this? When I currently read my raw register, it looks like this:
<img width="247" alt="image" src="https://github.com/dxoverdy/Alpha2MQTT/assets/53652614/eca890da-5c87-4989-8890-7c305147d3bc">
What should I enter in my Alpha Control dash to change it to yours, and also, if I want to change it back?
Thanks!

**Comment by dxoverdy** [comment]
Like so:

#define GRID_REGULATION_AL_10 10
#define GRID_REGULATION_AL_10_DESC "NRS097-2-1"
which is why yours currently returns raw data 0,10
#define GRID_REGULATION_AL_16 16
#define GRID_REGULATION_AL_16_DESC "G99"


`Alpha2MQTT/request/write/register/raw/data`

Set to G99
`{
    "registerAddress": "0x1000",
    "dataBytes": 2,
    "value": 16
}`

Set to NRS097-2-1
`{
    "registerAddress": "0x1000",
    "dataBytes": 2,
    "value": 10
}`
