### ISSUE TITLE
I can´t compile Alpha2MQTT

### ISSUE THREAD

**Issue by G1tHbUser** [dxoverdy/Alpha2MQTT#7]
Hi. Thx for yout Alpha2MQTT project.
I try to compile it, but Ide returns some errors.
Here is my log:

/
RegisterHandler.cpp: In constructor 'RegisterHandler::RegisterHandler()':
RegisterHandler.cpp:31:34: error: array used as initializer
RegisterHandler.cpp: In constructor 'RegisterHandler::RegisterHandler(RS485Handler*)':
RegisterHandler.cpp:41:54: error: array used as initializer

exit status 1

Compilation error: array used as initializer
/

Can You help me?
Thank You.

**Comment by dxoverdy** [comment]
Sorry I can’t advise anything really at this early stage.  Just make sure all the source files are in the same project folder and ensure you are attempting to compile for the right NodeMCU chip.
